@baseUri = http://localhost:3000/api
@json=Content-Type: application/json

###
GET {{baseUri}}/users

### 注册
POST {{baseUri}}/register
{{json}}

{
  "username": "user6",
  "password": "123456"
}

### 登录
POST {{baseUri}}/login
{{json}}

{
  "username": "user3",
  "password": "123456"
}
### 获取用户信息
GET {{baseUri}}/info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MDA0MTI3NmY4ZGU1NjdlMDA5MzIyOSIsImlhdCI6MTY3NzczOTQ4OX0.5N-wKLeKMdEvo0jjEzxBkxqemCac38YbMzUsQ1ly5cU